

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 polaroid-camera.glb 
Author: Boxroom 3D (https://sketchfab.com/Boxroom_3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/polaroid-camera-920ad62faa9d4aa48bc6e9535f3d07fe
Title: Polaroid Camera
*/


import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


export default function Model( props ) {
  const { nodes, materials } = useGLTF( '/models/polaroid_camera_compressed.glb' )
  return (
    <group {...props} dispose={null}>
      <group position={[2.051, 1.794, 1.181]}>
        <mesh geometry={nodes.Object_5.geometry} material={materials.orangestripr} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Negro01} />
      </group>
      <group position={[-0.967, 3.714, 1.175]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials.Blanco} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Gris} />
      </group>
      <group position={[0.002, 1.138, 0.394]}>
        <mesh geometry={nodes.Object_11.geometry} material={materials.Negro} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Blanco} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Blanco} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Rojo} />
      </group>
      <group position={[0.254, 1.609, -0.026]}>
        <mesh geometry={nodes.Object_16.geometry} material={materials.Negro} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.metal} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Gris} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Negro01} />
      </group>
      <group position={[-1.547, 0.543, 2.787]}>
        <mesh geometry={nodes.Object_22.geometry} material={materials.Azul} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Verde} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Amarillo} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Naranja} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Rojo} />
      </group>
      <group position={[0.127, 2.916, 1.23]}>
        <mesh geometry={nodes.Object_46.geometry} material={materials.Negro} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.Negro01} />
      </group>
      <mesh geometry={nodes.Object_28.geometry} material={materials.Blanco} position={[1.314, 2.788, 1.183]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Negro} position={[1.66, 0.411, -3.438]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.material} position={[-1.724, 3.164, 1.169]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Negro} position={[1.01, 2.24, 1.236]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.Amarillo} position={[1.686, 2.788, 1.124]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.Amarillo} position={[-1.635, 3.551, 0.324]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.Negro01} position={[0.2, 1.305, 2.608]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.material} position={[-0.978, 3.323, 1.169]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.Blanco01} position={[0.133, 0.321, 2.787]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Amarillo} position={[-1.622, 3.333, 0.467]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.material} position={[1.705, 3.455, 1.187]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.Gris} position={[1.686, 0.242, 2.787]} />
    </group>
  )
}

// useGLTF.preload( '/models/polaroid-camera.glb' )

