/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 house_09.gltf --transform
Author: Cyril Limoges Athiel (https://sketchfab.com/athiel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/house-09-cell-shading-8c19f685d15f4096b518a41dbcae5294
Title: House_09_Cell_Shading
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model( props ) {
  const { nodes, materials } = useGLTF('models/house_09_transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_Maison_09004_Mat_Rouge_0'].geometry} material={materials.Mat_Rouge} />
        <mesh geometry={nodes['01_Maison_09004_Mat_Rouge_01_0'].geometry} material={materials.Mat_Rouge_01} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_Maison_09005_Mat_Brique_0'].geometry} material={materials.Mat_Brique} castShadow receiveShadow />
        <mesh geometry={nodes['01_Maison_09005_Mat_Blanc_0'].geometry} material={materials.Mat_Blanc} castShadow receiveShadow />
        <mesh geometry={nodes['01_Maison_09005_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_Maison_09006_Mat_Blanc_0'].geometry} material={materials.Mat_Blanc} />
        <mesh geometry={nodes['01_Maison_09006_Mat_Gris_Dark_0'].geometry} material={materials.Mat_Gris_Dark} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_Maison_09007_Mat_Blanc_0'].geometry} material={materials.Mat_Blanc} />
        <mesh geometry={nodes['01_Maison_09007_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} />
        <mesh geometry={nodes['01_Maison_09007_Mat_Blanc002_0'].geometry} material={materials['Mat_Blanc.002']} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_Maison_09008_Mat_Gris_Marron_0'].geometry} material={materials.Mat_Gris_Marron} />
        <mesh geometry={nodes['01_Maison_09008_Mat_Metal_low_0'].geometry} material={materials.Mat_Metal_low} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_Maison_09012_Mat_Blanc_0'].geometry} material={materials.Mat_Blanc} />
        <mesh geometry={nodes['01_Maison_09012_Mat_Gris_Dark_0'].geometry} material={materials.Mat_Gris_Dark} />
        <mesh geometry={nodes['01_Maison_09012_Mat_Gris_Marron_0'].geometry} material={materials.Mat_Gris_Marron} />
        <mesh geometry={nodes['01_Maison_09012_Mat_Metal_low_0'].geometry} material={materials.Mat_Metal_low} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_Maison_09013_Mat_Gris_Dark_0'].geometry} material={materials.Mat_Gris_Dark} />
        <mesh geometry={nodes['01_Maison_09013_Mat_Metal_low_0'].geometry} material={materials.Mat_Metal_low} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_Maison_09014_Mat_Gris_Dark_0'].geometry} material={materials.Mat_Gris_Dark} />
        <mesh geometry={nodes['01_Maison_09014_Mat_Metal_low_0'].geometry} material={materials.Mat_Metal_low} />
        <mesh geometry={nodes['01_Maison_09014_Mat_Blanc_0'].geometry} material={materials.Mat_Blanc} />
        <mesh geometry={nodes['01_Maison_09014_MAT_Black_0'].geometry} material={materials.MAT_Black} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_Maison_09016_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} />
        <mesh geometry={nodes['01_Maison_09016_Mat_Gris_Marron_0'].geometry} material={materials.Mat_Gris_Marron} />
        <mesh geometry={nodes['01_Maison_09016_Mat_Blanc_0'].geometry} material={materials.Mat_Blanc} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_Maison_09017_MAT_ORANGE_low_0'].geometry} material={materials.MAT_ORANGE_low} />
        <mesh geometry={nodes['01_Maison_09017_MAT_Black_0'].geometry} material={materials.MAT_Black} />
        <mesh geometry={nodes['01_Maison_09017_Mat_Blanc_0'].geometry} material={materials.Mat_Blanc} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_Maison_09019_Mat_Gris_Dark_0'].geometry} material={materials.Mat_Gris_Dark} />
        <mesh geometry={nodes['01_Maison_09019_Mat_Metal_low_0'].geometry} material={materials.Mat_Metal_low} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_Maison_09022_Mat_Blanc_0'].geometry} material={materials.Mat_Blanc} />
        <mesh geometry={nodes['01_Maison_09022_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} />
        <mesh geometry={nodes['01_Maison_09022_Mat_Gris_Marron_0'].geometry} material={materials.Mat_Gris_Marron} />
        <mesh geometry={nodes['01_Maison_09022_Mat_Rouge_01_0'].geometry} material={materials.Mat_Rouge_01} />
        <mesh geometry={nodes['01_Maison_09022_Mat_Gris_Dark_0'].geometry} material={materials.Mat_Gris_Dark} />
        <mesh geometry={nodes['01_Maison_09022_Mat_Metal_low_0'].geometry} material={materials.Mat_Metal_low} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_Maison_09024_Mat_Gris_Dark_0'].geometry} material={materials.Mat_Gris_Dark} />
        <mesh geometry={nodes['01_Maison_09024_Mat_Rouge_01_0'].geometry} material={materials.Mat_Rouge_01} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_Maison_09025_MAT_Vert_0'].geometry} material={materials.MAT_Vert} />
        <mesh geometry={nodes['01_Maison_09025_MAT_Bleu_Ardoise_0'].geometry} material={materials.MAT_Bleu_Ardoise} />
        <mesh geometry={nodes['01_Maison_09025_Mat_Blanc_0'].geometry} material={materials.Mat_Blanc} />
        <mesh geometry={nodes['01_Maison_09025_Mat_Orange_medium_0'].geometry} material={materials.Mat_Orange_medium} />
        <mesh geometry={nodes['01_Maison_09025_Mat_Bois_0'].geometry} material={materials.Mat_Bois} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_Maison_09033_Mat_Orange_dark_0'].geometry} material={materials.Mat_Orange_dark} />
        <mesh geometry={nodes['01_Maison_09033_VERT_Herbe_0'].geometry} material={materials.VERT_Herbe} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_Maison_09034_MAT_Bleu_0'].geometry} material={materials.MAT_Bleu} />
        <mesh geometry={nodes['01_Maison_09034_MAT_Black_0'].geometry} material={materials.MAT_Black} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_Maison_09035_Mat_Fleur_02_0'].geometry} material={materials.Mat_Fleur_02} />
        <mesh geometry={nodes['01_Maison_09035_Mat_Fleur_0'].geometry} material={materials.Mat_Fleur} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['01_SOL_Maison_09006_MAT_Gris_Rue_0'].geometry} material={materials.MAT_Gris_Rue} />
        <mesh geometry={nodes['01_SOL_Maison_09006_Mat_Metal_low001_0'].geometry} material={materials['Mat_Metal_low.001']} />
        <mesh geometry={nodes['01_SOL_Maison_09006_MAT_Black002_0'].geometry} material={materials.MAT_Black} />
        <mesh geometry={nodes['01_SOL_Maison_09006_Mat_Gris_Dark001_0'].geometry} material={materials['Mat_Gris_Dark.001']} />
      </group>
      <mesh geometry={nodes['01_Maison_09_VERT_Herbe_0'].geometry} material={materials.VERT_Herbe} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09001_Mat_Bois_0'].geometry} material={materials.Mat_Bois} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09002_Mat_Gris_Dark_0'].geometry} material={materials.Mat_Gris_Dark} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09003_Mat_Rouge_01_0'].geometry} material={materials.Mat_Rouge_01} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09009_Mat_Metal_low_0'].geometry} material={materials.Mat_Metal_low} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09010_Mat_Metal_low_0'].geometry} material={materials.Mat_Metal_low} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09011_Mat_Metal_low_0'].geometry} material={materials.Mat_Metal_low} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09015_Mat_Bois_0'].geometry} material={materials.Mat_Bois} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09018_Mat_Gris_Dark_0'].geometry} material={materials.Mat_Gris_Dark} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09020_Mat_Gris_Dark_0'].geometry} material={materials.Mat_Gris_Dark} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09021_MAT_Black_0'].geometry} material={materials.MAT_Black} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09023_Mat_Bois_0'].geometry} material={materials.Mat_Bois} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09026_Mat_Orange_dark_0'].geometry} material={materials.Mat_Orange_dark} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09027_Mat_Rouge_0'].geometry} material={materials.Mat_Rouge} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09028_MAT_Black_0'].geometry} material={materials.MAT_Black} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09029_Mat_Bois_0'].geometry} material={materials.Mat_Bois} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09030_VERT_Herbe_0'].geometry} material={materials.VERT_Herbe} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09036_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09037_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09038_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09039_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09040_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09041_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09042_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09043_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09044_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09045_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09046_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09047_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09048_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09049_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09050_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09051_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09052_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09053_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09054_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09055_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09056_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09057_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09058_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09059_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09060_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09061_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09063_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09064_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09065_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09066_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09070_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09054_LINE001_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09048_LINE001_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09059_LINE001_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09061_LINE001_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09048_LINE002_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09048_LINE003_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09049_LINE001_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09059_LINE002_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09049_LINE002_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09061_LINE002_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_Maison_09036_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09001_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09002_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09003_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09004_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09005_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09007_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09008_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09009_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09010_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09011_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09012_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09013_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09014_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09015_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09016_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09017_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09018_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09019_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09020_Mat_Gris_Clair_0'].geometry} material={materials.Mat_Gris_Clair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Plane_Mat_Gris_Dark_0.geometry} material={materials.Mat_Gris_Dark} position={[0, 5.47, 135.88]} rotation={[-Math.PI / 2, 0, 0]} scale={[775.96, 710.61, 100]} />
      <mesh geometry={nodes['01_SOL_Maison_09021_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09022_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09023_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09024_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09025_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09026_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09027_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09028_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09029_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09030_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09031_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09032_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09033_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09034_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09035_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09036_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09037_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09038_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09039_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09040_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09041_LINE_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['01_SOL_Maison_09027_LINE001_LINE_0'].geometry} material={materials.LINE} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

// useGLTF.preload('models/house_09_transformed.glb')

