/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 polaroid_camera.gltf --transform
Author: Boxroom 3D (https://sketchfab.com/Boxroom_3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/polaroid-camera-920ad62faa9d4aa48bc6e9535f3d07fe
Title: Polaroid Camera
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model( props ) {
  const { nodes, materials } = useGLTF('models/polaroid_camera_v2_transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[2.05, 1.79, 1.18]}>
        <mesh geometry={nodes.Object_5.geometry} material={materials.orangestripr} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Negro01} />
      </group>
      <group position={[-0.97, 3.71, 1.17]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials.Blanco} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Gris} />
      </group>
      <group position={[0, 1.14, 0.39]}>
        <mesh geometry={nodes.Object_11.geometry} material={materials.Negro} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Blanco} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Blanco} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Rojo} />
      </group>
      <group position={[0.25, 1.61, -0.03]}>
        <mesh geometry={nodes.Object_16.geometry} material={materials.Negro} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.metal} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Gris} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Negro01} />
      </group>
      <group position={[-1.55, 0.54, 2.79]}>
        <mesh geometry={nodes.Object_22.geometry} material={materials.Azul} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Verde} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Amarillo} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Naranja} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Rojo} />
      </group>
      <group position={[0.13, 2.92, 1.23]}>
        <mesh geometry={nodes.Object_46.geometry} material={materials.Negro} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.Negro01} />
      </group>
      <mesh geometry={nodes.Object_28.geometry} material={materials.Blanco} position={[1.31, 2.79, 1.18]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Negro} position={[1.66, 0.41, -3.44]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.material} position={[-1.72, 3.16, 1.17]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Negro} position={[1.01, 2.24, 1.24]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.Amarillo} position={[1.69, 2.79, 1.12]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.Amarillo} position={[-1.63, 3.55, 0.32]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.Negro01} position={[0.2, 1.3, 2.61]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.material} position={[-0.98, 3.32, 1.17]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.Blanco01} position={[0.13, 0.32, 2.79]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Amarillo} position={[-1.62, 3.33, 0.47]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.material} position={[1.7, 3.45, 1.19]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.Gris} position={[1.69, 0.24, 2.79]} />
    </group>
  )
}

// useGLTF.preload('models/polaroid_camera_v2_transformed.glb')

